DROP TABLE IF EXISTS group_encryption_keys;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS media;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS chat_members;
DROP TABLE IF EXISTS chats;
DROP TABLE IF EXISTS users;
DROP EXTENSION IF EXISTS "uuid-ossp";